name: CI

env:
  IMAGE_NAME: meow-on-rails

on:
  push:
    branches:
      - main

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Move into e2e
        run: cd e2e
      
      - name: Install playwright
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --workers=1
        continue-on-error: true

      - name: Create zip file with Playwright report and test results
        run: zip -r reports.zip playwright-report/ test-results/
      
      - name: Upload combined report
        uses: actions/upload-artifact@v4
        with:
          name: combined-reports
          path: reports.zip
          retention-days: 30

      - name: Publish Test Summary Results
        run: npx github-actions-ctrf ctrf/ctrf-results.json

      - name: Check test results from JSON
        id: check-test-results
        run: |
          status=$(jq -r '.status' test-results/.last-run.json)
          if [ "$status" == "failed" ]; then
            echo "Tests failed"
            exit 1
          else
            echo "Tests passed"
          fi

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
            context: .
            push: true
            tags: |
              ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest